# Generated by Django 5.2.9 on 2025-12-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='emotion_tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
